version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x # Use a valid Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install # Install dependencies defined in package.json

  build:
    commands:
      - echo "Building the application..."
      - npm run build || echo "No build script found, skipping build step." # Run the build script if available

  post_build:
    commands:
      - echo "Zipping the build artifacts..."
      - zip -r build.zip . # Create a zip file of the entire directory
      - echo "Uploading build.zip to S3"
      - aws s3 cp build.zip s3://codebuild-cicd-monitoring/build.zip || echo "Failed to upload build.zip" # Replace with your S3 bucket path
      - echo "Upload completed successfully."

artifacts:
  files:
    - build.zip # Include the zip file in the build output
  discard-paths: yes # Discards file paths in the artifact output
  base-directory: . # Specify the base directory for zipping

cache:
  paths:
    - node_modules/**/* # Cache Node.js modules to speed up future builds
